WDP190401-15
michal-bootcamp/WDP-1904-01 pull request #14
Opened 2019-04-07 13:25 UTC by ypablo

Dodałem RWD dla tabletów i komórek - 2 elementy w rzędzie dla tabletów i jeden element dla komórek.

2019-04-11 21:39 UTC, OskarLebuda approved these changes

2019-04-11 21:39 UTC, OskarLebuda commented
rozwiąż proszę konflikty

2019-04-12 08:16 UTC, michal-bootcamp requested changes
build nie przechodzi, masz gdzies w pliku `src/sass/components/_post-box.scss` niedomkniety nawias

2019-04-13 12:32 UTC, ypablo commented
CSS był modyfikowany przez inną osobę. Mój lokalny plik css miał tylko 64 linie kodu, a niedomknięty nawias znajdował się w 97. W każdym razie, nawias został dodany i mam nadzieję, że już jest git :P

2019-04-16 09:05 UTC, michal-bootcamp commented
@ypablo takie sytuacje sie zdarzaja i trzeba sobie z nimi poradzic ;) wyglada ok

2019-04-16 09:05 UTC, michal-bootcamp approved these changes

2019-04-16 09:05 UTC, merged