Change 'post-box' html code and styles for hover
michal-bootcamp/WDP-1904-01 pull request #2
Opened 2019-04-04 11:32 UTC by Handzia

2019-04-10 20:07 UTC, tvardy requested changes
Do rozwiązania merge conflicts... bo w tym samym miejscu już Paweł coś zmieniał... ;) Poza tym OK ;)

2019-04-11 16:20 UTC, michal-bootcamp requested changes
test

2019-04-11 16:20 UTC, michal-bootcamp commented on src/partials/70_section-blog-posts.html
> +            <div class="cover" style="background-image:url('/images/blog/blog03.png');">
brzydki obrazek

2019-04-11 16:20 UTC, michal-bootcamp approved these changes

2019-04-11 16:26 UTC, merged