WDP190401-28
michal-bootcamp/WDP-1904-01 pull request #29
Opened 2019-04-27 16:28 UTC by Handzia

Zadaniem jest stworzenie wersji mobilnych sekcji "Galeria". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 

Na telefonach pokazujemy tylko taby ze sliderem (na 100% szerokości containera), a ukrywamy duże zdjęcie z prawej. 

W sliderze miniaturek ma być tyle elementów, ile zmieści się w całości na danej szerokości ekranu. Slider miniaturek powinno dać się przewijać również za pomocą swipe.

2019-04-29 15:26 UTC, ypablo approved these changes
RWD działa jak należy. Nie miałem możliwości sprawdzić czy galeria da się przewijać również za pomocą swipe, ale wyczytałem że tiny-slider ma ten element wbudowany domyślnie.

2019-04-30 07:04 UTC, michal-bootcamp requested changes
rozwiaz prosze konflikty

2019-05-09 17:25 UTC, michal-bootcamp requested changes
na widoku mobilnym na 320px mamy jeden obrazek w slajderze a przewijanie przewija o trzy slajdy zamiast o jeden

2019-05-10 13:15 UTC, michal-bootcamp approved these changes

2019-05-10 13:16 UTC, merged