WDP190401-6
michal-bootcamp/WDP-1904-01 pull request #3
Opened 2019-04-04 14:35 UTC by Handzia

Na karcie produktu ma być możliwość dodania starej ceny, która ma być przekreślona i widoczna tylko przy niektórych produktach. 
Rozwiązanie: 
Dla dotychczasowego diva z klasą .price nadałam display: flex; i umieściłam w nim przed guzikiem z ceną nowego diva .old-price. Ostylowałam zgodnie z designem.
Aby stara cena była widoczna tylko przy niektórych produktach, użyłam klasy .hidden wszędzie tam, gdzie cena ma być ukryta. Domyślnie stara cena jest widoczna.

2019-04-06 20:44 UTC, tvardy requested changes
Tam gdzie starej ceny ma nie być... lepiej po prostu nie wsadzać HTMLa dot. starej ceny ;)

Jeżeli już chcesz użyć class'y `.hidden`, to niech będzie ona zdefiniowana globalnie, a nie wewnątrz `.price`.

Użyłaś tu koloru `#a5a5a5`... jest on bardzo zbliżony, do koloru placeholdera z PR dot. zadania `-7`. Czy faktycznie potrzebujemy dwóch odcieni, czy może jednak możemy wybrać jeden z nich? ;)

2019-04-08 07:27 UTC, Handzia commented
Grzegorzu, zapisałam zmienną dla koloru i wyrzuciłam z html'a zgodnie z Twoją sugestią kod starej ceny, tam gdzie ma być ona niewidoczna. Chociaż muszę Ci powiedzieć, że celowo zrobiłam to wcześniej w ten sposób. Wydawało mi się, że ostatecznie to klient będzie decydował w którym produkcie ma być ta cena widoczna, a skoro tak, to łatwiej mu będzie potem operować klasą `hidden' na gotowym elemencie, niż samemu zastanawiać się, w którym miejscu umieścić kod i skąd go skopiować.

2019-04-10 19:23 UTC, tvardy commented
Gdyby ta stara cena miała być włączana/wyłączana po stronie JS, to jak najbardziej. Tu jednak zakładamy, że lista produktów będzie generowana przez back-end ;)

2019-04-10 19:23 UTC, tvardy approved these changes

2019-04-10 19:28 UTC, tvardy commented
Zdarzyła się tu jeszcze sytuacja, że wcześniej z-merge'owałem zadanie Dominika, które zmieniało podobne rejony HTMLa. Tak więc masz do rozwiązania proste konflikty... ;) Trzymam kciuki.

2019-04-11 09:49 UTC, merged