WDP-190401-2
michal-bootcamp/WDP-1904-01 pull request #8
Opened 2019-04-05 12:25 UTC by ypablo

Zmodyfikowałem css koszyka tak aby duża liczba produktów (więcej niż 999) nie zachodziła na ikonę koszyka i nie zasłaniała jej.

2019-04-05 15:26 UTC, tvardy requested changes
A gdyby tak spozycjonować całość po drugiej (lewej) stronie? Mielibyśmy łatwiej z zadaniami dot. RWD ;) Wrzucam bardzo szybki podgląd, jak mogłoby to wyglądać... nie dopieszczałem samej ikonki koszyka... ;)
<img width="113" alt="Screenshot 2019-04-05 at 17 23 40" src="https://user-images.githubusercontent.com/694872/55638616-e8f52880-57c7-11e9-8ee1-63b83dff7aea.png">

2019-04-05 22:25 UTC, ypablo commented
Dopieściłem ikonkę ;)

2019-04-06 20:24 UTC, tvardy requested changes

2019-04-06 20:24 UTC, tvardy commented on src/partials/10_header.html
> +            <div class="cart-counter">123456789</div>
miało być maksymalnie 5 cyfr 😉 😛

2019-04-06 20:24 UTC, tvardy commented on src/sass/components/_header.scss
> +          padding-right: 5px;
proponuję zmienić na `padding-right: 7px` ;)

2019-04-06 20:24 UTC, tvardy commented on src/sass/components/_header.scss
> +          justify-content: right;
proponuję zmienić na `justify-content: flex-end;`

2019-04-07 12:05 UTC, ypablo commented on src/sass/components/_header.scss
> +          justify-content: right;
Gotowe! :)

2019-04-10 18:57 UTC, tvardy approved these changes

2019-04-10 18:58 UTC, merged