WDP190401-11
michal-bootcamp/WDP-1904-01 pull request #9
Opened 2019-04-05 14:38 UTC by Handzia

Nadałam responsywność dla głównego menu. Na desktopie zostawiłam menu bez zmian. Na tabletach ustawiłam wyszukiwanie pod menu. Na telefonach - menu jest ukryte, a widoczne jest tylko wyszukiwanie i przycisk hamburger, który po kliknięciu rozwija menu.

2019-04-08 06:23 UTC, OskarLebuda requested changes

2019-04-08 06:23 UTC, OskarLebuda commented on src/sass/components/_header.scss
> +      /*height: 84px;*/
jeśli jest to zakomentowane, to czy w takim razie potrzebujemy w ogóle tą regułę?

2019-04-08 06:23 UTC, OskarLebuda commented on src/sass/components/_header.scss
> +          i:first-child {
Obie reguły posiadają względnie podobne własności, może da się to jakoś połączyć?

2019-04-08 06:23 UTC, OskarLebuda commented on src/sass/components/_header.scss
> +          i:first-child {
chodzi oczywiście o ten `:first-child` i `last-child`

2019-04-08 06:23 UTC, OskarLebuda commented on src/sass/components/_header.scss
> +          input {
nadajmy temu inputowi jakąś klasę i stylujmy klasę zamiast gołego elementu

2019-04-08 06:23 UTC, OskarLebuda commented on src/sass/components/_header.scss
> +    flex-direction: column-reverse;
Nie wiem, czy nie lepszym rozwiązaniem byłoby gdyby "szukajka" była nad menu, a nie pod nim

2019-04-08 15:24 UTC, Handzia commented
Oskar, naniosłam poprawki wg Twoich wskazówek. 
Zmieniłam też trochę kod wyszukiwania na telefonach tak, żeby select i input były jeden pod drugim. 
Wcisnęłam z rozpędu "Resolve conversation" w Twoim komentarzu odnośnie umiejscowienia "szukajki" i mi gdzieś zaginął. Ale wydaje mi się, że może lepiej zostawić to tak, jak jest w treści zadania. W tasku 7 dodałam do selecta kilka opcji do wyboru i w tej chwili select będzie się rozwijał w dół nie zakrywając menu. Gdyby "szukajka" była nad menu, to select by się rozwijał na menu...

2019-04-30 06:38 UTC, michal-bootcamp requested changes
Thumbs do usuniecia
dla przypomnienia: https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

2019-05-01 13:14 UTC, michal-bootcamp approved these changes

2019-05-01 13:14 UTC, merged